#!/bin/bash

options=""
if [ -t 0 ]; then
  options="${options}"
fi

docker build --tag test --quiet --file Dockerfile.dev . &> /dev/null &&
docker run --rm${options} -i \
  --net=host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(which docker):/bin/docker \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -e HOME \
  -e PYTHONPATH=$(pwd)/features/:$(pwd)/features/support/ \
  test "$@"
