#!/bin/bash

docker build --tag test --quiet --file bin/Dockerfile.dev . &> /dev/null &&
docker run --rm -i \
  --net=host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(which docker):/bin/docker \
  -v ${HOME}:${HOME} \
  -w $(pwd) \
  -e HOME \
  -e PYTHONPATH=$(pwd)/features/:$(pwd)/features/support/ \
  test "$@"
